apiVersion: v1
kind: Service
metadata:
  name: kaniko-app-service
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: kaniko-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
